version: '3'

services:
  postgres:
    image: postgres:10-alpine
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      PGDATA: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    volumes:
      - "/var/lib/images-uploading-services/postgresql/data:/var/lib/postgresql/data"

  rails:
    build: .
    environment:
      IMAGE_UPLOADING_SERVICE_DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      IMAGE_UPLOADING_SERVICE_DATABASE_USER: postgres
      IMAGE_UPLOADING_SERVICE_DATABASE_HOST: postgres
      IMAGE_UPLOADING_SERVICE_DEFAULT_HOST: ${DEFAULT_HOST}
      RAILS_ENV: production
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      PORT: 3000
    ports:
      - "3000:3000"
    volumes:
      - "./storage:/app/image-uploading-services/storage"
    depends_on:
      - postgres
