version: '3'

services:
  postgres:
    image: postgres:10-alpine
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      PGDATA: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    volumes:
      - "./data/postgres:/var/lib/postgresql/data"

  rails:
    build: .
    environment:
      IMAGE_UPLOADING_SERVICE_DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      IMAGE_UPLOADING_SERVICE_DATABASE_USER: postgres
      IMAGE_UPLOADING_SERVICE_DATABASE_HOST: postgres
      RAILS_ENV: production
      PORT: 3000
    ports:
      - "3000:3000"
    depends_on:
      - postgres
